### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by WeeshawChen** [huitangtang/DADA-AAAI2020#3]
At first, I want to use my own dataset, it came across an error, 
`IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number`
I found it in trainer.py
I thought it was the dataset problem, so I used the office31 as the training dataset, but still got the same problem
`IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number`
would you please tell me if there is something wrong with my confs?

![image](https://user-images.githubusercontent.com/49385033/81637138-32db2400-9448-11ea-8f7e-a26fc43cc1a4.png)

**Comment by huitangtang** [comment]
Hi, I think it is a problem of PyTorch version. You can just follow the prompt message of the reported error. For the one-element tensor, e.g. losses and prec1, you can replace tensor[0] with tensor.item().Best regards,Hui Tang发自我的华为手机-------- 原始邮件 --------发件人： WeeshawChen <notifications@github.com>日期： 2020年5月12日周二 中午12:01收件人： huitangtang/DADA-AAAI2020 <DADA-AAAI2020@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [huitangtang/DADA-AAAI2020] IndexError (#3)
At first, I want to use my own dataset, it came across an error,
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
I found it in trainer.py
I thought it was the dataset problem, so I used the office31 as the training dataset, but still got the same problem
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
would you please tell me if there is something wrong with my confs?

**Comment by WeeshawChen** [comment]
![image](https://user-images.githubusercontent.com/49385033/81668385-31752000-9477-11ea-9917-c7e6c14cba09.png)

**Comment by WeeshawChen** [comment]
Well, thanks for your instant replying. 
I googled it before you reply, 
![image](https://user-images.githubusercontent.com/49385033/81673511-5a4ce380-947e-11ea-8d39-d7481b3ad29a.png)
Just as same as you said, but I still don't get it that how to change the code here
![image](https://user-images.githubusercontent.com/49385033/81673762-b31c7c00-947e-11ea-8486-48c81edcdc68.png)
